name: Generate Language Stats

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: DenverCoder1/readme-stats-action@v1
        with:
          username: notzeman
          output: ./stats
          stats: languages
          theme: transparent
          hide_border: true
          exclude_forks: true
          exclude_archived: true
